# Generated by Django 2.1.5 on 2019-04-13 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Atsakymo tekstas')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Ar teisingas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinimo data')),
            ],
            options={
                'verbose_name': 'Klausimo atsakymas',
                'verbose_name_plural': 'Klausimo atsakymai',
            },
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_finished', models.BooleanField(default=False, verbose_name='Ar žaidimas baigtas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinimo data')),
                ('answered', models.ManyToManyField(related_name='won_games', to='rukla.Answer', verbose_name='Pasirinkti teisingi atsakymai')),
                ('failed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_games', to='rukla.Answer', verbose_name='Pasirinktas neteisingas atsakymas')),
            ],
            options={
                'verbose_name': 'Žaidimas',
                'verbose_name_plural': 'Žaidimai',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Klausimo tekstas')),
                ('explanation', models.TextField(verbose_name='Klausimo paaiškinimas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinimo data')),
            ],
            options={
                'verbose_name': 'Žaidimo klausimas',
                'verbose_name_plural': 'Žaidimo klausimai',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Pavadinimas')),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Rangas',
                'verbose_name_plural': 'Rangai',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rukla.Rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vartotojo informacija',
                'verbose_name_plural': 'Vartotojų informacijos',
            },
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='rukla.UserInfo', verbose_name='Vartotojo informacija'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='rukla.Question'),
        ),
    ]
