# Generated by Django 2.1.5 on 2019-04-13 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rukla', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Žaidimo klausimas', 'verbose_name_plural': 'Žaidimo klausimai'},
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
