# Generated by Django 2.1.5 on 2019-04-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rukla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='questions',
            field=models.ManyToManyField(blank=True, to='rukla.Question', verbose_name='Žaidimo klausimai'),
        ),
    ]
