# Generated by Django 2.1.5 on 2019-04-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rukla', '0002_gamestatus_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestatus',
            old_name='failed',
            new_name='failed_answer',
        ),
        migrations.RemoveField(
            model_name='gamestatus',
            name='answered',
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, related_name='won_games', to='rukla.Question', verbose_name='Pasirinkti teisingi atsakymai'),
        ),
    ]
