# Generated by Django 2.1.5 on 2019-04-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rukla', '0002_auto_20190413_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamestatus',
            options={'verbose_name': 'Žaidimas', 'verbose_name_plural': 'Žaidimai'},
        ),
    ]
