# Generated by Django 2.1.5 on 2019-04-13 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rukla', '0003_auto_20190413_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rukla.Rank', verbose_name='Rangas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rukla.Rank', verbose_name='Rangas'),
        ),
    ]
