# Generated by Django 2.1.5 on 2019-04-13 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rukla', '0003_auto_20190413_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Ar žaidimas baigtas'),
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='answered',
            field=models.ManyToManyField(related_name='won_games', to='rukla.Answer', verbose_name='Pasirinkti teisingi atsakymai'),
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='failed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_games', to='rukla.Answer', verbose_name='Pasirinktas neteisingas atsakymas'),
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='rukla.UserInfo', verbose_name='Vartotojo informacija'),
        ),
    ]
