version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  "migrations/**",
]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  type_checker = "mypy"