# Generated by Django 3.0.4 on 2020-04-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_squashed_0019_auto_20200418_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amžius'),
        ),
        migrations.AddField(
            model_name='pet',
            name='cat_friendly',
            field=models.BooleanField(blank=True, null=True, verbose_name='Draugiškas katėms'),
        ),
        migrations.AddField(
            model_name='pet',
            name='child_friendly',
            field=models.BooleanField(blank=True, null=True, verbose_name='Draugiškas vaikams'),
        ),
        migrations.AddField(
            model_name='pet',
            name='desexed',
            field=models.BooleanField(blank=True, help_text='Pažymėkite jei gyvūnas yra kastruotas arba sterilizuotas', null=True, verbose_name='Kastruotas ar sterilizuotas'),
        ),
        migrations.AddField(
            model_name='pet',
            name='dog_friendly',
            field=models.BooleanField(blank=True, null=True, verbose_name='Draugiškas šunims'),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(None, 'Nepatikslinta'), (1, 'Patinas'), (2, 'Patelė')], null=True, verbose_name='Lytis'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_special_care_needed',
            field=models.BooleanField(blank=True, help_text='Pasirinkite taip, jei gyvūnas yra traumuotas, jam reikalinga ypatinga pagalba ir  gali paimti tik žmogus turintis patirties.', null=True, verbose_name='Reikalinga speciali pagalba'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_vaccinated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Vakcinuotas'),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.IntegerField(blank=True, choices=[(None, 'Nepatikslinta'), (1, 'Mažas'), (2, 'Vidutinis'), (3, 'Didelis')], null=True, verbose_name='Dydis'),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Svoris'),
        ),
    ]
