# Generated by Django 2.1.2 on 2018-11-16 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181019_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=web.models.PetProfilePhoto._pet_photo_file, verbose_name='Gyvūno nuotrauka')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gyvūno nuotrauka',
                'verbose_name_plural': 'Gyvūnų nuotraukos',
                'ordering': ['pet', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Gyvūnas', 'verbose_name_plural': 'Gyvūnai'},
        ),
        migrations.AlterModelOptions(
            name='shelter',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Gyvūnų prieglauda', 'verbose_name_plural': 'Gyvūnų prieglaudos'},
        ),
        migrations.AddField(
            model_name='shelter',
            name='authenticated_users',
            field=models.ManyToManyField(blank=True, help_text='Priskirti vartotojai gali matyti prieglaudos gyvūnus ir juos tvarkyti.', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojai tvarkantys prieglaudos informaciją'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Amžius'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(help_text='Gyvūno aprašymas matomas įėjus į gyvūno profilį.', verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Gyvūno vardas'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(upload_to=web.models.Pet._pet_photo_file, verbose_name='Gyvūno nuotrauka'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(help_text='Prieglauda, kurioje šiuo metu randasi gyvūnas', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='web.Shelter', verbose_name='Prieglauda'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='short_description',
            field=models.CharField(help_text='Trumpas aprašymas apie gyvūną rodomas programėlės pagrindiniame ekrane skirtas pritraukti varototojus paspausti ant gyvūno profilio.', max_length=64, verbose_name='Trumpas aprašymas'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atnaujinimo data'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Elektroninis paštas'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Prieglaudos pavadinimas'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone',
            field=models.CharField(max_length=24, verbose_name='Telefono numeris'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atnaujinimo data'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/users/', verbose_name='Vartotojo nuotrauka'),
        ),
        migrations.AddField(
            model_name='petprofilephoto',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_photos', to='web.Pet'),
        ),
    ]
