# Generated by Django 3.0.4 on 2020-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200419_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='cat_friendly',
            field=models.BooleanField(blank=True, choices=[(None, 'Nepatikslinta'), (True, 'Taip'), (False, 'Ne')], null=True, verbose_name='Draugiškas su katėmis'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='child_friendly',
            field=models.BooleanField(blank=True, choices=[(None, 'Nepatikslinta'), (True, 'Taip'), (False, 'Ne')], null=True, verbose_name='Draugiškas su vaikais'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='desexed',
            field=models.BooleanField(blank=True, choices=[(None, 'Nepatikslinta'), (True, 'Taip'), (False, 'Ne')], help_text='Pažymėkite jei gyvūnas yra kastruotas arba sterilizuotas', null=True, verbose_name='Kastruotas ar sterilizuotas'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='dog_friendly',
            field=models.BooleanField(blank=True, choices=[(None, 'Nepatikslinta'), (True, 'Taip'), (False, 'Ne')], null=True, verbose_name='Draugiškas su šunimis'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_special_care_needed',
            field=models.BooleanField(blank=True, choices=[(None, 'Nepatikslinta'), (True, 'Taip'), (False, 'Ne')], help_text='Pasirinkite taip, jei gyvūnas yra traumuotas, jam reikalinga ypatinga pagalba ir  gali paimti tik žmogus turintis patirties.', null=True, verbose_name='Reikalinga speciali pagalba'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_vaccinated',
            field=models.BooleanField(blank=True, choices=[(None, 'Nepatikslinta'), (True, 'Taip'), (False, 'Ne')], null=True, verbose_name='Vakcinuotas'),
        ),
    ]
