# Generated by Django 2.1.2 on 2018-11-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20181116_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petprofilephoto',
            options={'ordering': ['order'], 'verbose_name': 'Gyvūno nuotrauka', 'verbose_name_plural': 'Gyvūnų nuotraukos'},
        ),
    ]
