# Generated by Django 3.0.4 on 2020-04-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200419_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpetchoice',
            name='is_favorite',
            field=models.BooleanField(db_index=True, verbose_name='Vartotojas pamėgo gyvūną'),
        ),
    ]
