# Generated by Django 2.1.2 on 2018-11-17 21:19

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20181116_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petprofilephoto',
            options={'ordering': ['order'], 'verbose_name': 'Gyvūno profilio nuotrauka', 'verbose_name_plural': 'Gyvūnų profilio nuotraukos'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AlterField(
            model_name='petprofilephoto',
            name='photo',
            field=models.ImageField(upload_to=web.models.PetProfilePhoto._pet_photo_file, verbose_name='Gyvūno profilio nuotrauka'),
        ),
    ]
