# Generated by Django 3.0.4 on 2020-04-23 16:31

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200419_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='square_logo',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.Shelter._shelter_square_logo_file, verbose_name='Kvadratinis logotipas'),
        ),
    ]
