# Generated by Django 2.1.2 on 2018-11-19 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20181117_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetPetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', enumfields.fields.EnumIntegerField(default=1, enum=web.models.GetPetRequestStatus)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinimo data')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_pet_requests', to='web.Pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_pet_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Noras priglausti gyvūną',
                'verbose_name_plural': 'Norai priglausti gyvūnus',
                'default_related_name': 'get_pet_requests',
            },
        ),
        migrations.AlterUniqueTogether(
            name='getpetrequest',
            unique_together={('user', 'pet')},
        ),
    ]
