# Generated by Django 2.1.2 on 2018-11-19 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181119_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getpetrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_pet_requests', to='web.Pet', verbose_name='Gyvūnas'),
        ),
        migrations.AlterField(
            model_name='getpetrequest',
            name='status',
            field=enumfields.fields.EnumIntegerField(default=1, enum=web.models.GetPetRequestStatus, help_text='Pasirenkamas vienas iš gyvūno statusų pas potencialų šeimininką', verbose_name='Gyvūno statusas'),
        ),
        migrations.AlterField(
            model_name='getpetrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_pet_requests', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
    ]
