# Generated by Django 2.1.2 on 2018-11-20 11:20

from django.db import migrations
import enumfields.fields
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20181119_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=enumfields.fields.EnumIntegerField(db_index=True, default=1, enum=web.models.PetStatus, help_text='Pažymėjus gyvūną, kaip laukiantį šeiminką jis bus rodomas programėlėje.', verbose_name='Gyvūno statusas'),
        ),
    ]
