# Generated by Django 2.1.2 on 2018-11-20 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_pet_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPetChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(verbose_name='Vartotojas pamėgo gyvūną')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinimo data')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_pet_choices', to='web.Pet', verbose_name='Gyvūnas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_pet_choices', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas')),
            ],
            options={
                'verbose_name': 'Vartotojo gyvūno pasirinkimaas',
                'verbose_name_plural': 'Vartotojų gyvūnų pasirinkimai',
                'default_related_name': 'users_pet_choices',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userpetchoice',
            unique_together={('user', 'pet')},
        ),
    ]
