# Generated by Django 3.0.4 on 2020-04-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200429_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='legal_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Įstaigos pavadinimas'),
        ),
    ]
