# Generated by Django 3.0.4 on 2020-04-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200429_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='information_for_getpet_team',
            field=models.TextField(blank=True, help_text='Įrašykite informaciją skirtą GetPet komandai pvz: žmogaus kontaktinę informaciją dėl GetPet mentoriaus priskyrimo.', null=True, verbose_name='Informacija skirta GetPet komandai'),
        ),
    ]
