# Generated by Django 2.1.2 on 2018-11-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20181120_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpetchoice',
            options={'default_related_name': 'users_pet_choices', 'ordering': ['-id'], 'verbose_name': 'Vartotojo gyvūno pasirinkimaas', 'verbose_name_plural': 'Vartotojų gyvūnų pasirinkimai'},
        ),
    ]
