# Generated by Django 2.1.5 on 2019-01-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190109_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getpetrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_pet_requests', to='web.Pet', verbose_name='Gyvūnas'),
        ),
    ]
