# Generated by Django 3.0.4 on 2020-05-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20200430_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Gyvūno savybė')),
                ('pets', models.ManyToManyField(blank=True, related_name='_petproperty_pets_+', to='web.Pet', verbose_name='Gyvūnai')),
            ],
            options={
                'verbose_name': 'Gyvūno savybė',
                'verbose_name_plural': 'Gyvūno savybės',
                'ordering': ['name'],
                'default_related_name': 'properties',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='_pet_properties_+', to='web.PetProperty', verbose_name='Gyvūno savybės'),
        ),
    ]
