# Generated by Django 2.1.5 on 2019-04-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20190118_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
