# Generated by Django 3.0.4 on 2020-05-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200501_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.IntegerField(choices=[(None, 'Nepatikslinta'), (1, 'Patinas'), (2, 'Patelė')], null=True, verbose_name='Lytis'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.IntegerField(choices=[(None, 'Nepatikslinta'), (1, 'Mažas'), (2, 'Vidutinis'), (3, 'Didelis')], null=True, verbose_name='Dydis'),
        ),
    ]
