# Generated by Django 2.2.2 on 2019-06-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_user_social_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Šalies pavadinimas')),
                ('code', models.CharField(help_text='Šalies kodas pagal ISO 3166 alpha 2 standartą pvz: lt, lv', max_length=2, unique=True, verbose_name='Šalies kodas')),
            ],
            options={
                'verbose_name': 'Šalis',
                'verbose_name_plural': 'Šalys',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Regiono pavadinimas')),
                ('code', models.CharField(help_text='Unikalus regiono kodas pvz: ankara', max_length=32, unique=True, verbose_name='Regiono kodas')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='web.Country')),
            ],
            options={
                'verbose_name': 'Regionas',
                'verbose_name_plural': 'Regionai',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='shelter',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shelters', to='web.Region', verbose_name='Regionas'),
        ),
    ]
