# Generated by Django 3.0.4 on 2020-05-01 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20200501_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofilephoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Sukūrimo data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petprofilephoto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
        migrations.AddField(
            model_name='petprofilephoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atnaujinimo data'),
        ),
    ]
