# Generated by Django 3.0.5 on 2020-05-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20200501_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_vaccinated',
        ),
    ]
