# Generated by Django 3.0.6 on 2020-05-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20200503_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petproperty',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Gyvūno savybė'),
        ),
    ]
