# Generated by Django 3.0.4 on 2020-04-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20190623_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.IntegerField(choices=[(1, 'Laukia šeimininko'), (2, 'Laikinai paimtas per GetPet'), (3, 'Paimtas visam laikui per GetPet'), (4, 'Paimtas ne per GetPet')], db_index=True, default=1, help_text='Pažymėjus gyvūną, kaip laukiantį šeiminką jis bus rodomas programėlėje.', verbose_name='Gyvūno statusas'),
        ),
    ]
