# Generated by Django 3.0.4 on 2020-04-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20200418_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getpetrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Noras paimti gyvūną'), (2, 'Gyvūnas laikinai pasiimtas'), (3, 'Gyvūnas gražintas po laikinos globos'), (4, 'Gyvūnas pasiimtas visam laikui')], default=1, help_text='Pasirenkamas vienas iš gyvūno statusų pas potencialų šeimininką', verbose_name='Gyvūno statusas'),
        ),
    ]
