# Generated by Django 3.0.6 on 2020-05-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_pet_taken_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='special_information',
            field=models.TextField(blank=True, help_text='Pavyzdžiui: amputuota galūnė, specialūs sveikatos poreikiai  ir/ar būklės (reikalingi medikamentai, šlapimo nelaikymas ar kt.)', null=True, verbose_name='Svarbi informacija'),
        ),
    ]
