# Generated by Django 3.0.6 on 2020-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_pet_special_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='special_information',
            field=models.TextField(blank=True, help_text='Pavyzdžiui: amputuota galūnė, reikalingi medikamentai, šlapimo nelaikymas, specialūs sveikatos poreikiai ir būklės', null=True, verbose_name='Svarbi informacija'),
        ),
    ]
