# Generated by Django 3.0.6 on 2020-05-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20200508_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='special_information',
            field=models.TextField(blank=True, help_text='Pavyzdžiui: amputuota galūnė, šlapimo nelaikymas, reikalingi medikamentai ir kita.', null=True, verbose_name='Specialūs sveikatos poreikiai ir būklės'),
        ),
    ]
