# Generated by Django 3.0.6 on 2020-05-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20200508_1226'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
