# Generated by Django 3.0.6 on 2020-05-10 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20200510_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='authenticated_users',
            field=models.ManyToManyField(blank=True, help_text='Priskirti vartotojai gali matyti prieglaudos gyvūnus ir juos tvarkyti.', limit_choices_to=models.Q(groups__name='Shelter'), related_name='shelters', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojai tvarkantys prieglaudos informaciją'),
        ),
    ]
