# Generated by Django 3.0.6 on 2020-05-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20200510_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Svoris'),
        ),
    ]
