# Generated by Django 3.0.6 on 2020-05-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20200512_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.IntegerField(choices=[(1, 'Laukia šeimininko'), (2, 'Laikinai paimtas per GetPet'), (3, 'Paimtas visam laikui per GetPet'), (4, 'Paimtas ne per GetPet')], db_index=True, default=1, help_text='Gyvūnai su statusu laukiantys šeimininko yra rodomi programėlėje.', verbose_name='Gyvūno statusas'),
        ),
    ]
