# Generated by Django 3.0.6 on 2020-05-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20200512_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.SmallIntegerField(choices=[(None, 'Nepatikslinta'), (1, 'Patinas'), (2, 'Patelė')], null=True, verbose_name='Lytis'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.SmallIntegerField(choices=[(None, 'Nepatikslinta'), (1, 'Mažas'), (2, 'Vidutinis'), (3, 'Didelis')], null=True, verbose_name='Dydis'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Laukia šeimininko'), (2, 'Laikinai paimtas per GetPet'), (3, 'Paimtas visam laikui per GetPet'), (4, 'Paimtas ne per GetPet')], db_index=True, default=1, help_text='Gyvūnai su statusu laukiantys šeimininko yra rodomi programėlėje.', verbose_name='Gyvūno statusas'),
        ),
    ]
