# Generated by Django 3.0.6 on 2020-06-03 16:07

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20200513_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='square_logo',
            field=models.ImageField(upload_to=web.models.Shelter._shelter_square_logo_file, verbose_name='Kvadratinis logotipas'),
        ),
    ]
