# Generated by Django 3.0.6 on 2020-06-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20200603_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Vietos platuma'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Vietos ilguma'),
        ),
    ]
