# Generated by Django 3.0.6 on 2020-06-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20200605_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vietos platuma'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vietos ilguma'),
        ),
    ]
