# Generated by Django 3.0.7 on 2020-06-05 21:52

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_auto_20200605_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Vardas')),
                ('photo', models.ImageField(upload_to=web.models.TeamMember._team_member_photo_file, verbose_name='Nuotrauka')),
                ('role', models.CharField(max_length=128, verbose_name='Rolė')),
                ('email', models.EmailField(max_length=254, verbose_name='El. paštas')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinimo data')),
            ],
            options={
                'verbose_name': 'Komandos narys',
                'verbose_name_plural': 'Komandos nariai',
                'ordering': ['order'],
            },
        ),
    ]
