# Generated by Django 3.0.7 on 2020-06-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Gyvūno vardas'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Prieglaudos pavadinimas'),
        ),
    ]
