# Generated by Django 3.0.7 on 2020-06-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20200606_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
