# Generated by Django 3.0.7 on 2020-06-06 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_auto_20200606_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='authenticated_users',
            field=models.ManyToManyField(blank=True, help_text='Priskirti vartotojai gali matyti prieglaudos gyvūnus ir juos tvarkyti.', limit_choices_to=models.Q(('connector', 'OR'), ('groups__name', 'Shelter'), ('is_staff', True)), related_name='shelters', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojai tvarkantys prieglaudos informaciją'),
        ),
    ]
