# Generated by Django 3.0.7 on 2020-06-08 16:02

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_auto_20200608_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(help_text='Rekomenduojamas profilio nuotraukos kraštinių santykis 3:4', upload_to=web.models.Pet._pet_photo_file, verbose_name='Vertikali gyvūno profilio nuotrauka'),
        ),
    ]
