# Generated by Django 3.0.7 on 2020-06-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_auto_20200608_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Amžius'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='desexed',
            field=models.BooleanField(verbose_name='Kastruotas / sterilizuotas'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.SmallIntegerField(choices=[(None, 'Nepatikslinta'), (1, 'Patinas'), (2, 'Patelė')], verbose_name='Lytis'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.SmallIntegerField(choices=[(None, 'Nepatikslinta'), (1, 'Mažas'), (2, 'Vidutinis'), (3, 'Didelis')], verbose_name='Dydis'),
        ),
    ]
