# Generated by Django 3.0.7 on 2020-06-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_auto_20200613_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atnaujinimo data'),
        ),
    ]
