# Generated by Django 3.0.7 on 2020-06-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_auto_20200613_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='desexed',
            field=models.BooleanField(choices=[(None, 'Nepatikslinta'), (True, 'Taip'), (False, 'Ne')], verbose_name='Kastruotas / sterilizuotas'),
        ),
    ]
