# Generated by Django 3.0.7 on 2020-07-02 12:13

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_auto_20200625_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Vardas')),
                ('photo', models.ImageField(upload_to=web.models.Mentor._mentor_photo_file, verbose_name='Nuotrauka')),
                ('description', models.TextField(verbose_name='Aprašymas')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinimo data')),
            ],
            options={
                'verbose_name': 'Mentorius',
                'verbose_name_plural': 'Mentoriai',
            },
        ),
    ]
