# Generated by Django 3.0.7 on 2020-07-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_mentor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['order'], 'verbose_name': 'Mentorius', 'verbose_name_plural': 'Mentoriai'},
        ),
        migrations.AddField(
            model_name='mentor',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
