# Generated by Django 3.0.7 on 2020-07-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_auto_20200702_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='order',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterIndexTogether(
            name='pet',
            index_together={('order', 'id')},
        ),
    ]
