# Generated by Django 3.0.7 on 2020-07-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_auto_20200709_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Gyvūnas', 'verbose_name_plural': 'Gyvūnai'},
        ),
    ]
