# Generated by Django 3.0.7 on 2020-07-09 15:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_postgis'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Vieta'),
        ),
    ]
