# Generated by Django 3.0.7 on 2020-07-09 18:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_shelter_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='shelter',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Vieta'),
        ),
    ]
