# Generated by Django 3.0.7 on 2020-07-10 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0052_auto_20200710_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='properties',
        ),
        migrations.DeleteModel(
            name='PetProperty',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='dog_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='dog_properties',
            new_name='properties',
        ),

    ]
