# Generated by Django 3.0.7 on 2020-07-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0053_auto_20200710_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Pažymėjus prieglauda matoma viešai',
                                      verbose_name='Paskelbta'),
        ),
    ]
