name: Test, build Docker image and deploy to production
on:
  push:
    branches:
      - master
jobs:
  name: Test GetPet WEB
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_HOST: localhost
      POSTGRES_USER: getpet
      POSTGRES_PASSWORD: getpet
      POSTGRES_DB: getpet
      DEV: 1

    services:
      postgres:
        image: postgres:12.2
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python -m pip install -r requirements.txt
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run tests
        run: python manage.py test

  build:
    name: Build and push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set GIT commit and branch
        id: git_vars
        run: |
          echo ::set-env name=GIT_COMMIT::$(git rev-parse --short HEAD)
          echo ::set-env name=GIT_BRANCH::$(git rev-parse --abbrev-ref HEAD)

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: vycius/getpet-platform
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: ${{ github.event_name != 'schedule' }}
          buildargs: GIT_COMMIT,GIT_BRANCH

      #      - name: Create a Sentry.io release
      #        uses: tclindner/sentry-releases-action@v1.1.0
      #        env:
      #          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #          SENTRY_ORG: getpet
      #          SENTRY_PROJECT: getpet-web
      #        with:
      #          tagName: ${{ GITHUB_SHA }}
      #          environment: production


  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.TARGET }}
            git pull
            make