name: Build Docker image and Deploy to production
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set GIT commit and branch
        id: git_vars
        run: |
          echo ::set-env name=GIT_COMMIT::$(git rev-parse --short HEAD)
          echo ::set-env name=GIT_BRANCH::$(git rev-parse --abbrev-ref HEAD)

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: vycius/getpet-platform
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: ${{ github.event_name != 'schedule' }}
          buildargs: GIT_COMMIT,GIT_BRANCH

      #      - name: Create a Sentry.io release
      #        uses: tclindner/sentry-releases-action@v1.1.0
      #        env:
      #          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #          SENTRY_ORG: getpet
      #          SENTRY_PROJECT: getpet-web
      #        with:
      #          tagName: ${{ GITHUB_SHA }}
      #          environment: production

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.TARGET }}
            git pull
            make
